location = /cla {
    return 308 /cla/;
}

location /cla/ {
    try_files $uri $uri/ /cla/index.html;
}

location = /cod {
    return 308 /cod/;
}

location /cod/ {
    try_files $uri $uri/ /cod/index.html;
}
